services:
  api:
    build:
      context: ./api
    container_name: gestor_clases_api
    environment:
      - FLASK_APP=database
      - MYSQL_DATABASE=data
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '8000:8000'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - gestor_clases
    volumes:
      - ./api:/app

  front:
    build:
      context: ./front
    container_name: gestor_clases_front
    environment:
      - API_BASE_URL=http://gestor_clases_api:8000
      - PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - '3000:4321'
    restart: unless-stopped
    networks:
      - gestor_clases
    volumes:
      - ./front:/app

  db:
    image: mysql
    container_name: gestor_clases_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=data
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 1s
      retries: 20
    networks:
      - gestor_clases

networks:
  gestor_clases:
