services:
  api:
    build:
      context: ./api
    container_name: project_manager_api
    ports:
      - '8001:8000'
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    networks:
      - project_manager
    volumes:
      - ./api:/app

  front_dev:
    build:
      context: ./front
    container_name: project_manager_front_dev
    ports:
      - '5322:4321'
    restart: unless-stopped
    networks:
      - project_manager
    volumes:
      - ./front:/app

  front:
    build:
      context: ./front
    container_name: project_manager_front_prod
    working_dir: /app
    ports:
      - '5321:4321'
    restart: unless-stopped
    depends_on:
      - api
    networks:
      - project_manager
    volumes:
      - ./front:/app
    command: sh -c "npm install && npm run build && npm run preview"

  db:
    image: mysql
    container_name: project_manager_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=data
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - 3307:3306
    command: --event_scheduler=ON
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 2s
      timeout: 1s
      retries: 20
    networks:
      - project_manager

networks:
  project_manager:
